server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: matchus-image
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

jwt:
  header: token
  issuer: matchus
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 3000
