spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:db/schema_new.sql
      data-locations: classpath:db/data_new.sql
      encoding: UTF-8
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
