server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: localhost
    port: 6379

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

cloud:
  aws:
    s3:
      bucket: matchus-image
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
